### ISSUE TITLE
[BUG] Settings pages inaccessible

### ISSUE THREAD

**Issue by SLinxTheFox** [A5b84/status-effect-bars#11]
Seems like an invalid character is in the path of your settings pages if i understand this correctly

I get crash code -1
"The game crashed whilst rendering screen
Error: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: iconic:textures/gui/icons/left to right.png"

**Comment by A5b84** [comment]
I feel like this is most likely not related to my mod (maybe [this one](https://modrinth.com/mod/iconic) instead?), can you send your logs so I can check?

**Comment by SLinxTheFox** [comment]
I don't use Iconic, but here's my crash log. happens any time i click on one of the two settings pages that aren't the first one.
[crash-2023-05-29_15.48.13-client.txt](https://github.com/A5b84/status-effect-bars/files/11594422/crash-2023-05-29_15.48.13-client.txt)

**Comment by A5b84** [comment]
Just gave it a look, it was an issue in Visual Overhaul ([here](https://github.com/TeamMidnightDust/VisualOverhaul/issues/41)) and it was fixed in version 5.0.1 two days ago so everything should be fine now

**Comment by SLinxTheFox** [comment]
thank you so much!
