### ISSUE TITLE
[BUG] HUD UI rendering in the wrong Position

### ISSUE THREAD

**Issue by HB-Stratos** [A5b84/status-effect-bars#21]
No matter what I set the position to in the settings, the icons appear in the top middle-ish of the screen. Not sure if this a mod incompatibility of some sort. 
![image](https://github.com/A5b84/status-effect-bars/assets/56313836/1ab5006b-86e3-49cf-b798-582a6ffd4af3)
here's a log:
[w8uH7we.txt](https://github.com/A5b84/status-effect-bars/files/15267239/w8uH7we.txt)

Thanks in Advance for giving this a look!

**Comment by HB-Stratos** [comment]
I just noticed trying around that it does happen all the time. I didn't realize the effect indicators themselves were vanilla... what I get for playing so little survival. So not really a mod bug I guess. Still quite confused about what is causing it. 
But I guess I can close this.

**Comment by A5b84** [comment]
Not sure what's the cause either but a safe guess would be that it's probably a HUD related mod

**Comment by HB-Stratos** [comment]
For future reference: I found the issue.
Journeymap has an issue where the position of the effect indicators can get messed up when the window scaling is changed. Fix this by going into journeymap - settings - minimap - position (at the bototm of the menu) - drag the effect indicators back to where they belong.

**Comment by SanQianQVQ** [comment]
> For future reference: I found the issue.供将来参考：我发现了这个问题。 Journeymap has an issue where the position of the effect indicators can get messed up when the window scaling is changed. Fix this by going into journeymap - settings - minimap - position (at the bototm of the menu) - drag the effect indicators back to where they belong.Journeymap 存在一个问题，即当窗口缩放比例发生更改时，效果指示器的位置可能会变得混乱。通过进入旅程地图 - 设置 - 小地图 - 位置（位于菜单底部） - 将效果指示器拖回其所属位置来修复此问题。

Hero!
