### ISSUE TITLE
HUD does not work

### ISSUE THREAD

**Issue by nmsltr** [A5b84/status-effect-bars#22]
I don’t even know the approximate reason, I removed all possible mod conflicts and still the HUD did not work. Logs and list of mods are below.

https://mclo.gs/aEBO7qd
[Turtle MP 0.21.txt](https://github.com/A5b84/status-effect-bars/files/15377599/Turtle.MP.0.21.txt)

**Comment by A5b84** [comment]
Can you try narrowing it down (e.g. using [binary split search](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a))?

Also what do you mean by the HUD not working, is it just that the bars aren't visible or is it something else? (By default bars aren't shown for permanent effects and beacon effects)

**Comment by nmsltr** [comment]
Effect elements in the game do not work, but everything is ok in the inventory

**Comment by A5b84** [comment]
If you mean that the gray boxes on the top right of the screen are not visible then there's a good chance it's caused by another mod, so try disabling this mod (status effect bars) temporarily to see if the issue still happens

Otherwise you'll have to be more specific because I still have no idea what you mean

**Comment by nmsltr** [comment]
Yes Yes Yes! That's exactly what I'm talking about. Is there a list of mods that may conflict?

**Comment by A5b84** [comment]
No there's no known conflict with other mods

Does the issue happen when the mod is not installed?

**Comment by A5b84** [comment]
In that case it's not a bug from my mod so I can't help you, I'd still recommend trying the thing I linked earlier https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a
