### ISSUE TITLE
Status effect bars isn't displayed when used with ImmediatelyFast

### ISSUE THREAD

**Issue by warofzen** [A5b84/status-effect-bars#6]
Tested on an instance with only status effect bar, cloth config, and [ImmediatelyFast](https://github.com/RaphiMC/ImmediatelyFast)

[Logfile](https://mclo.gs/uTd4OTg)

**Comment by ZmanisCoollol** [comment]
fixed now in latest immediatelyfast release

**Comment by A5b84** [comment]
Good to hear, I'll close this (and sorry for the inactivity)

(For future reference, the relevant commit is [RaphiMC/ImmediatelyFast/commit/021f2ba3217b9973b63a77a71952c690a8569a5c](https://github.com/RaphiMC/ImmediatelyFast/commit/021f2ba3217b9973b63a77a71952c690a8569a5c)
